[programs.localnet]
spl_staking = "9AheNuTjeEHkMGzZQi22P8bkK2sJa8DKe2LYZk58XXmk"
[programs.devnet]
spl_staking = "9AheNuTjeEHkMGzZQi22P8bkK2sJa8DKe2LYZk58XXmk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/wstar/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
